"""change task status to enum

Revision ID: b5c53c0a15aa
Revises: 6d2e96b647ed
Create Date: 2026-02-02 08:00:37.983757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c53c0a15aa'
down_revision = '6d2e96b647ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               type_=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
